version: "3"
services:
  app:
    container_name: app
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7500:7500"
    volumes:
      - .:/app
      - /app/node_modules/
